/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.*;
import java.io.*;
import javax.swing.*;
import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.util.Random;

/**
 *
 * @author cesar
 */
public class Transferencia extends javax.swing.JFrame {

    private String dato;
    
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs = null; 
    
    Random random = new Random();
    int codigo = 100000 + random.nextInt(900000);
    
    public Transferencia() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        llenarRFCs();   
        scaleImage3();
    }
    
    public void scaleImage3(){
    ImageIcon icon = new ImageIcon("C:\\Users\\cesar\\Downloads\\role_user_icon_217169 (1).png");
    Image img = icon.getImage();
    Image imgScale = img.getScaledInstance(Icon2.getWidth(), Icon2.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    Icon2.setIcon(scaledIcon);
    }
    
    
    
        public void generarPDF(int cantidadRetirada, int nuevoSaldo, String RFCSeleccionado) {
        Document document = new Document();
        try {
            String filePath = "C:\\Users\\cesar\\Documents\\NetBeansProjects\\BancoAgain2\\ChequesTransferencias\\Retiro.pdf";
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filePath));

            document.open();

            // Contenido del PDF
            Paragraph title = new Paragraph("CHEQUE TRANSFERENCIA");
            document.add(title);

            // Agregar espacio entre párrafos
            document.add(new Paragraph("")); // Párrafo vacío

            document.add(new Paragraph("BANCO XALAPEÑO 2024"));
            document.add(new Paragraph("Comprobante de Transferencia"));
            document.add(new Paragraph(""));
            document.add(new Paragraph(""));
            document.add(new Paragraph("Se ha retirado $" + cantidadRetirada + " de su cuenta y se ha transferido esa cantidad a: " + RFCSeleccionado));
            document.add(new Paragraph("Su nuevo saldo es: $" + nuevoSaldo));
            document.add(new Paragraph("Código de Transferencia; "+codigo));
            document.add(new Paragraph("Gracias por su preferencia :D"));

            // Agregar imagen
            String imagePath = "C:\\Users\\cesar\\Desktop\\Carpeta del Banco\\Logo.png";
            try {
                com.lowagie.text.Image image = com.lowagie.text.Image.getInstance(imagePath);
                image.scaleAbsolute(5f * 28.33f, 5f * 28.33f); // Escalar la imagen a 10x10 cm
                document.add(image);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al cargar la imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, "Cheque generado exitosamente.");
            document.close();
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al generar el PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (document != null && document.isOpen()) {
                document.close();
            }
        }
    }
    
    public void setDato(String dato){
        this.dato = dato;
        NombreTrans.setText(dato);
    }
    
    private void llenarRFCs(){
    try {
        cn = con.getConnection();
        st = cn.createStatement();
        String nombreSeleccionado = NombreTrans.getText();
        rs = st.executeQuery("SELECT RFC FROM Clientes WHERE Nombre != '" + nombreSeleccionado + "' AND RFC NOT IN (SELECT RFC FROM Clientes WHERE Nombre = '" + nombreSeleccionado + "')");
        
        RFCombo.removeAllItems();
        
        while (rs.next()) {
            String rfc = rs.getString("RFC");
            RFCombo.addItem(rfc);
        }
        
    } catch(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar los RFC: "+ e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RFCombo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NombreTrans = new javax.swing.JLabel();
        Icon2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Hind Madurai Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 106));
        jLabel1.setText("TRANSFERENCIA");

        jButton1.setBackground(new java.awt.Color(200, 212, 210));
        jButton1.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 106));
        jButton1.setText("Cerrar Sesión");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Hind Madurai Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 106));
        jLabel3.setText("RFC:");

        RFCombo.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        RFCombo.setForeground(new java.awt.Color(0, 102, 106));
        RFCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RFCombo.setBorder(null);
        RFCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFComboActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(146, 205, 226));
        jButton3.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 106));
        jButton3.setText("$100");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(146, 205, 226));
        jButton2.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 106));
        jButton2.setText("$500");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(146, 205, 226));
        jButton4.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 106));
        jButton4.setText("$250");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(146, 205, 226));
        jButton5.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 106));
        jButton5.setText("$1000");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Hind Madurai Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 106));
        jLabel2.setText("Nombre del usuario:");

        NombreTrans.setFont(new java.awt.Font("Hind Madurai Light", 1, 14)); // NOI18N
        NombreTrans.setForeground(new java.awt.Color(0, 102, 106));

        jPanel2.setBackground(new java.awt.Color(146, 205, 226));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel5.setForeground(new java.awt.Color(0, 102, 106));
        jLabel5.setText("¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RFCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RFCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Icon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
        String rfcDestino = RFCombo.getSelectedItem().toString();
        String nombreUsuario = NombreTrans.getText();
        
        // Obtener RFC del usuario actual
        String rfcUsuarioActual = "";
        Statement st = cn.createStatement();
        ResultSet rsRfcUsuario = st.executeQuery("SELECT RFC FROM Clientes WHERE Nombre = '" + nombreUsuario + "'");
        if (rsRfcUsuario.next()) {
            rfcUsuarioActual = rsRfcUsuario.getString("RFC");
        }
        
        if (rfcDestino.equals(rfcUsuarioActual)) {
            JOptionPane.showMessageDialog(this, "No puedes transferir saldo a tu misma cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si se intenta transferir a la misma cuenta
        }
        
        // Continuar con el resto del código de transferencia si no es la misma cuenta
        
        // Obtener saldo del destinatario
        String query = "SELECT Saldo FROM Clientes WHERE RFC = '" + rfcDestino + "'";
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            int saldoDestino = rs.getInt("Saldo");
            int cantidadATransferir = 100; // Cantidad a transferir
            String querySaldoUsuario = "SELECT Saldo FROM Clientes WHERE Nombre = '" + nombreUsuario + "'";
            ResultSet rsSaldoUsuario = st.executeQuery(querySaldoUsuario);
            if (rsSaldoUsuario.next()) {
                int saldoUsuario = rsSaldoUsuario.getInt("Saldo");
                if (saldoUsuario >= cantidadATransferir) {
                    // Realizar la transferencia actualizando el saldo en la base de datos
                    int nuevoSaldoDestino = saldoDestino + cantidadATransferir;
                    int nuevoSaldoUsuario = saldoUsuario - cantidadATransferir;
                    String updateQueryDestino = "UPDATE Clientes SET Saldo = " + nuevoSaldoDestino + " WHERE RFC = '" + rfcDestino + "'";
                    String updateQueryUsuario = "UPDATE Clientes SET Saldo = " + nuevoSaldoUsuario + " WHERE Nombre = '" + nombreUsuario + "'";
                    st.executeUpdate(updateQueryDestino);
                    st.executeUpdate(updateQueryUsuario);
                    JOptionPane.showMessageDialog(this, "Transferencia realizada correctamente, su código: "+codigo);

                    // Definir cantidadRetirada y nuevoSaldo aquí
                    int cantidadRetirada = cantidadATransferir;
                    int nuevoSaldo = nuevoSaldoUsuario;

                    // Generar PDF
                    String rfcSeleccionado = RFCombo.getSelectedItem().toString();
                    generarPDF(cantidadRetirada, nuevoSaldo, rfcSeleccionado);
                } else {
                    JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para realizar la transferencia.");
                }
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al realizar la transferencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
        String rfcDestino = RFCombo.getSelectedItem().toString();
        String nombreUsuario = NombreTrans.getText();
        
        // Obtener RFC del usuario actual
        String rfcUsuarioActual = "";
        Statement st = cn.createStatement();
        ResultSet rsRfcUsuario = st.executeQuery("SELECT RFC FROM Clientes WHERE Nombre = '" + nombreUsuario + "'");
        if (rsRfcUsuario.next()) {
            rfcUsuarioActual = rsRfcUsuario.getString("RFC");
        }
        
        if (rfcDestino.equals(rfcUsuarioActual)) {
            JOptionPane.showMessageDialog(this, "No puedes transferir saldo a tu misma cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si se intenta transferir a la misma cuenta
        }
        
        // Continuar con el resto del código de transferencia si no es la misma cuenta
        
        // Obtener saldo del destinatario
        String query = "SELECT Saldo FROM Clientes WHERE RFC = '" + rfcDestino + "'";
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            int saldoDestino = rs.getInt("Saldo");
            int cantidadATransferir = 250; // Cantidad a transferir
            String querySaldoUsuario = "SELECT Saldo FROM Clientes WHERE Nombre = '" + nombreUsuario + "'";
            ResultSet rsSaldoUsuario = st.executeQuery(querySaldoUsuario);
            if (rsSaldoUsuario.next()) {
                int saldoUsuario = rsSaldoUsuario.getInt("Saldo");
                if (saldoUsuario >= cantidadATransferir) {
                    // Realizar la transferencia actualizando el saldo en la base de datos
                    int nuevoSaldoDestino = saldoDestino + cantidadATransferir;
                    int nuevoSaldoUsuario = saldoUsuario - cantidadATransferir;
                    String updateQueryDestino = "UPDATE Clientes SET Saldo = " + nuevoSaldoDestino + " WHERE RFC = '" + rfcDestino + "'";
                    String updateQueryUsuario = "UPDATE Clientes SET Saldo = " + nuevoSaldoUsuario + " WHERE Nombre = '" + nombreUsuario + "'";
                    st.executeUpdate(updateQueryDestino);
                    st.executeUpdate(updateQueryUsuario);
                    JOptionPane.showMessageDialog(this, "Transferencia realizada correctamente.");

                    // Definir cantidadRetirada y nuevoSaldo aquí
                    int cantidadRetirada = cantidadATransferir;
                    int nuevoSaldo = nuevoSaldoUsuario;

                    // Generar PDF
                    String rfcSeleccionado = RFCombo.getSelectedItem().toString();
                    generarPDF(cantidadRetirada, nuevoSaldo, rfcSeleccionado);
                } else {
                    JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para realizar la transferencia.");
                }
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al realizar la transferencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        String rfcDestino = RFCombo.getSelectedItem().toString();
        String nombreUsuario = NombreTrans.getText();
        
        // Obtener RFC del usuario actual
        String rfcUsuarioActual = "";
        Statement st = cn.createStatement();
        ResultSet rsRfcUsuario = st.executeQuery("SELECT RFC FROM Clientes WHERE Nombre = '" + nombreUsuario + "'");
        if (rsRfcUsuario.next()) {
            rfcUsuarioActual = rsRfcUsuario.getString("RFC");
        }
        
        if (rfcDestino.equals(rfcUsuarioActual)) {
            JOptionPane.showMessageDialog(this, "No puedes transferir saldo a tu misma cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si se intenta transferir a la misma cuenta
        }
        
        // Continuar con el resto del código de transferencia si no es la misma cuenta
        
        // Obtener saldo del destinatario
        String query = "SELECT Saldo FROM Clientes WHERE RFC = '" + rfcDestino + "'";
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            int saldoDestino = rs.getInt("Saldo");
            int cantidadATransferir = 500; // Cantidad a transferir
            String querySaldoUsuario = "SELECT Saldo FROM Clientes WHERE Nombre = '" + nombreUsuario + "'";
            ResultSet rsSaldoUsuario = st.executeQuery(querySaldoUsuario);
            if (rsSaldoUsuario.next()) {
                int saldoUsuario = rsSaldoUsuario.getInt("Saldo");
                if (saldoUsuario >= cantidadATransferir) {
                    // Realizar la transferencia actualizando el saldo en la base de datos
                    int nuevoSaldoDestino = saldoDestino + cantidadATransferir;
                    int nuevoSaldoUsuario = saldoUsuario - cantidadATransferir;
                    String updateQueryDestino = "UPDATE Clientes SET Saldo = " + nuevoSaldoDestino + " WHERE RFC = '" + rfcDestino + "'";
                    String updateQueryUsuario = "UPDATE Clientes SET Saldo = " + nuevoSaldoUsuario + " WHERE Nombre = '" + nombreUsuario + "'";
                    st.executeUpdate(updateQueryDestino);
                    st.executeUpdate(updateQueryUsuario);
                    JOptionPane.showMessageDialog(this, "Transferencia realizada correctamente.");

                    // Definir cantidadRetirada y nuevoSaldo aquí
                    int cantidadRetirada = cantidadATransferir;
                    int nuevoSaldo = nuevoSaldoUsuario;

                    // Generar PDF
                    String rfcSeleccionado = RFCombo.getSelectedItem().toString();
                    generarPDF(cantidadRetirada, nuevoSaldo, rfcSeleccionado);
                } else {
                    JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para realizar la transferencia.");
                }
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al realizar la transferencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {
        String rfcDestino = RFCombo.getSelectedItem().toString();
        String nombreUsuario = NombreTrans.getText();
        
        String rfcUsuarioActual = "";
        Statement st = cn.createStatement();
        ResultSet rsRfcUsuario = st.executeQuery("SELECT RFC FROM Clientes WHERE Nombre = '" + nombreUsuario + "'");
        if (rsRfcUsuario.next()) {
            rfcUsuarioActual = rsRfcUsuario.getString("RFC");
        }
        
        if (rfcDestino.equals(rfcUsuarioActual)) {
            JOptionPane.showMessageDialog(this, "No puedes transferir saldo a tu misma cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        String query = "SELECT Saldo FROM Clientes WHERE RFC = '" + rfcDestino + "'";
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            int saldoDestino = rs.getInt("Saldo");
            int cantidadATransferir = 1000; // Cantidad a transferir
            String querySaldoUsuario = "SELECT Saldo FROM Clientes WHERE Nombre = '" + nombreUsuario + "'";
            ResultSet rsSaldoUsuario = st.executeQuery(querySaldoUsuario);
            if (rsSaldoUsuario.next()) {
                int saldoUsuario = rsSaldoUsuario.getInt("Saldo");
                if (saldoUsuario >= cantidadATransferir) {
                    // Realizar la transferencia actualizando el saldo en la base de datos
                    int nuevoSaldoDestino = saldoDestino + cantidadATransferir;
                    int nuevoSaldoUsuario = saldoUsuario - cantidadATransferir;
                    String updateQueryDestino = "UPDATE Clientes SET Saldo = " + nuevoSaldoDestino + " WHERE RFC = '" + rfcDestino + "'";
                    String updateQueryUsuario = "UPDATE Clientes SET Saldo = " + nuevoSaldoUsuario + " WHERE Nombre = '" + nombreUsuario + "'";
                    st.executeUpdate(updateQueryDestino);
                    st.executeUpdate(updateQueryUsuario);
                    JOptionPane.showMessageDialog(this, "Transferencia realizada correctamente.");

                    // Definir cantidadRetirada y nuevoSaldo aquí
                    int cantidadRetirada = cantidadATransferir;
                    int nuevoSaldo = nuevoSaldoUsuario;

                    // Generar PDF
                    String rfcSeleccionado = RFCombo.getSelectedItem().toString();
                    generarPDF(cantidadRetirada, nuevoSaldo, rfcSeleccionado);
                } else {
                    JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para realizar la transferencia.");
                }
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al realizar la transferencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void RFComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFComboActionPerformed

    }//GEN-LAST:event_RFComboActionPerformed


    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel NombreTrans;
    private javax.swing.JComboBox<String> RFCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}


